name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.10.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.10.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: "ORRJZCO-YDB88609"
          SF_USERNAME: "azamatt"
          SF_ROLE: "ACCOUNTADMIN"
          SF_WAREHOUSE: "COMPUTE_WH"
          SF_DATABASE: "DEMO_DB"
          SNOWFLAKE_PASSWORD: "Snowflake2014@"
          SF_OCSP_FAIL_OPEN: "true"
          SNOWFLAKE_OCSP_FAIL_OPEN: "true"
        run: |
          pip install schemachange
          pip install certifi==2025.7.14
          pip install snowflake-connector-python==3.16.0
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
