name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Configure and Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          pip install schemachange

          echo "Step 1: Creating connections.toml"
          echo '[default]' > connections.toml
          echo "account = \"${SF_ACCOUNT}\"" >> connections.toml
          echo "user = \"${SF_USERNAME}\"" >> connections.toml
          echo "password = \"${SNOWFLAKE_PASSWORD}\"" >> connections.toml
          echo "role = \"${SF_ROLE}\"" >> connections.toml
          echo "warehouse = \"${SF_WAREHOUSE}\"" >> connections.toml
          echo "database = \"${SF_DATABASE}\"" >> connections.toml
          echo "disable_ocsp_checks = true" >> connections.toml

          echo "Step 2: Creating schemachange.yml"
          echo "root-folder: \"${GITHUB_WORKSPACE}/migrations\"" > schemachange.yml
          echo "change-history-table: \"${SF_DATABASE}.SCHEMACHANGE.CHANGE_HISTORY\"" >> schemachange.yml
          echo "create-change-history-table: true" >> schemachange.yml
          echo "verbose: true" >> schemachange.yml
          
          echo "Step 3: Running schemachange"
          schemachange
